### ISSUE TITLE
Incompatability with Smart Coupons store credits

### ISSUE THREAD

**Issue by tyler-paulson** [taxjar/taxjar-woocommerce-plugin#134]
We're experiencing the same issue that appeared to have been fixed in April with PR #98 but we are experiencing them today with the latest versions of all plugins.

To isolate the issue from our custom code, I spun up a limited test environment with the following  installed:

```
WordPress 5.2.3
WooCommerce 3.7.1
WooCommerce Subscriptions 2.6.1
WooCommerce Stripe Gateway 4.2.5
WooCommerce Smart Coupons 4.3.0
Tax Jar 3.0.10
```

As soon as calculations with TaxJar are enabled, the store credit Smart Coupon stops applying the credit to orders. Here's a screenshot:

Before enabling: <a href="https://cl.ly/d46679997790" target="_blank">https://cl.ly/d46679997790</a>
After enabling: <a href="https://cl.ly/b97eca8be0f4" target="_blank">https://cl.ly/b97eca8be0f4</a>

Steps to reproduce:

1. Add [this product](https://wc.tylerpaulson.com/product/box-of-books) to cart
2. Add a shipping city/state/zip on cart page
3. Apply coupon code 577ed3q3aminc (should be a store credit for $80)

This is a critical piece of a new feature we're in the process of rolling out for [TBR](https://mytbr.co). I'm happy to assist in any way I can with testing code changes, etc. Thank you!

**Comment by dallendalton** [comment]
@tyler-paulson We have been able to replicate and confirm this bug on our end. It currently only occurs with subscription products. We should have a fix out early next week. Thanks!

**Comment by tyler-paulson** [comment]
Thank you @dallendalton for the quick response! We appreciate it.

**Comment by dallendalton** [comment]
@tyler-paulson - We have been digging into this issue and believe we know the cause. However, we are unable to fix it in our plugin. 

In the Smart Coupons plugin there is code that checks to ensure the plugin does not apply the store credit more than once. Normally this works without issue, however our plugin has to force WooCommerce to recalculate the cart totals a second time which has previously caused a conflict with their plugin. It looks like in version 4.0.8 of their plugin they resolved the issue for normal products, however it does not appear to resolve it for subscription products. Due to the way their check is built and applied, there isn't a fix at this time that we can apply to our plugin to resolve the issue. We recommend reaching out to them to see if they can fix it from their end.

The check I mentioned is contained in the smart_coupons_after_calculate_totals method of the class-wc-smart-coupons.php file in their plugin. It fails due to apply the store credit due to the smart_coupons_after_calculate_totals action being run more than the woocommerce_cart_reset when both the TaxJar (or WooCommerce Services) plugin is active and there is a subscription product in the cart.

**Comment by tyler-paulson** [comment]
@dallendalton Thanks for explaining that so thoroughly. It definitely helped us find a solution. We reached out to the developers of Smart Coupons and they're going to be adding a filter that allows the value of `$stop_at` to be modified by custom code. We're using a preliminary version now of that change which has solved this issue for us.
