### ISSUE TITLE
Sync doesn't work unless I enable Tax Calculation

### ISSUE THREAD

**Issue by khag7** [taxjar/taxjar-woocommerce-plugin#164]
I want to sync orders to TaxJar but I'm not yet ready to have tax calculated by this plugin for customers buying in my store.

I had the backfill queue full of old orders, they're all stuck at "Awaiting".

I believe the WC_Taxjar_Transaction_Sync::init() is not getting past the first line
`if ( apply_filters( 'taxjar_enabled', isset( $this->taxjar_integration->settings['enabled'] ) && 'yes' == $this->taxjar_integration->settings['enabled'] ) ) {`

Is this by design? I don't understand why you can't allow me to sync orders until I enable. I would think that you should be checking the "taxjar_download" setting instead (and change the filter name to match):
`if ( apply_filters( 'taxjar__download_enabled', isset( $this->taxjar_integration->settings['taxjar_download'] ) && 'yes' == $this->taxjar_integration->settings['taxjar_download'] ) ) {`

**Comment by dallendalton** [comment]
Hi @khag7, thanks for submitting your question.

So you are correct in what is preventing transaction sync from working. This was intentional when the plugin was created as choosing to not utilize TaxJar for sales tax calculations will mean that there will be inaccuracies in the tax calculations and collections. This could lead to increased liability when filing the taxes.

I would like to learn a little more about your use case for syncing transactions to TaxJar but not wanting TaxJar to provide the calculations. Is there a particular business process that makes this desirable? Or is there something that makes you uncomfortable with enabling tax calculations through the TaxJar plugin? Any additional info you provide could be helpful as we discuss internally if allowing only transaction sync without calculations is something that we want to support.

Thanks!

**Comment by dallendalton** [comment]
Hi @khag7 ,

Update on this issue, we have decided that we do want to support enabling transaction sync separately from the tax calculation functionality. I don't have a for sure ETA on the change but most likely it will be included in our next release. I will update this issue with more information as it is available. Thanks!

**Comment by dallendalton** [comment]
This change went out in the 3.2.3 release.
