### ISSUE TITLE
Programatically updating subscriptions with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by tyler-paulson** [taxjar/taxjar-woocommerce-plugin#169]
I work as a developer on [TBR](https://mytbr.co/). We offer our subscription product in both physical and digital forms and collect tax on neither, one or both depending on the jurisdiction. We allow customers to switch subscription levels. To maintain control of the UX, we've making the switches programmatically with PHP:

Here's out current setup:

```
WordPress 5.4.2
WooCommerce 4.6.1
WooCommerce Subscriptions 3.09
TaxJar 3.2.3
```

This is roughly the code we're using to make the switch (there's some code above that determine whether the switch is allowed and adds shipping info for subscriptions that need it):

```php

$subscription = new WC_Subscription($_POST['subscription']);
$variation = new WC_Product_Variation($variation_id);

$subscription->remove_order_items();
$subscription->add_product($variation);

if($_POST['phys'] == 'physical') {
    $shipping_rate = new WC_Shipping_Rate();
    if($_POST['freq'] == 'quarterly') {
        $shipping_rate->set_cost(floatval(PHYSICAL_QUARTERLY_SHIPPING));
    }
    $subscription->add_shipping($shipping_rate);
}

$subscription->set_billing_interval($interval);
$subscription->set_billing_period($period);

$subscription->calculate_totals();
$subscription->save();
```

When I built this out originally, I noted that `calculate_totals()` calls `calculate_taxes()` which I assumed TaxJar hooked into. I've been looking into the code and it appears that it works differently. We've had a few instances now where someone has switched from a untaxed to a taxed product and not been charged tax when their renewal processed.

Can you point me to how I'd go about doing this? Thanks!

**Comment by dallendalton** [comment]
@tyler-paulson Thanks for your patience is waiting for a response and we apologize for such a long delay. I have taken a look at your code and believe I have a solution and some additional information for you.

The TaxJar plugin does not currently hook into the calculate_totals or calculate_taxes methods on the order object. This is due to various reasons but most of them relate back to supporting older versions of WooCommerce. However, since we now only officially support back to WooCommerce 3.2.0 and will be tightening our support for older versions in the future, we are going to take a look at reworking major portions of how our tax calculation is applied to both orders and the cart.

In the meantime I believe I have a solution that should work for you using this line of code:

TaxJar()->calculate_order_tax( $subscription );

Place this right above this line:

$subscription->calculate_totals();

Once that is done, your subscriptions should also have the correct tax after you have done your dynamic updates to them.

Please let me know if you run into any problems with this,

Thanks!

**Comment by tyler-paulson** [comment]
Thank you for the response @dallendalton!

We received a note from TaxJar support suggesting that we manually initiate the `woocommerce_before_save_order_items` action in our code. While fully confirming this has been a bit tricky since users don't take the action too often it appears that it has solved the issue which makes sense as I just took a look at the plugin code and I believe that action causes the method you referenced to be called.
