### ISSUE TITLE
Tax exempt customer has taxes applied to subscription and renewals

### ISSUE THREAD

**Issue by devinsays** [taxjar/taxjar-woocommerce-plugin#186]
We have a customer that with a tax exemption set in their profile:
<img width="980" alt="Screen Shot 2021-04-20 at 3 01 01 PM" src="https://user-images.githubusercontent.com/431879/115456951-65a9a280-a1e9-11eb-80ef-3b4ade56a2a7.png">

They have been getting charged tax on their subscription renewals, even though they are tax exempt.

If I remove the product from their subscription and add it fresh there are no taxes. But when "Recalculate" is done, the taxes are added.

![go6xYpPiIJ](https://user-images.githubusercontent.com/431879/115457227-d81a8280-a1e9-11eb-87cc-ca77d60d02fb.gif)

How can we ensure that all our tax exempt customers are not charged tax on their subscriptions?

**Comment by dallendalton** [comment]
@devinsays - Thanks for bringing this issue to our attention. We have been able to replicate it and are working on a fix. 

Also, while tax is being incorrectly added to the subscription when manually triggering the totals recalculation, it won't actually charge your customers an incorrect amount. When a renewal order is created tax is calculated again on the renewal order (to ensure the correct tax is applied if rates have changed since the subscription was created). We have confirmed that the bug is isolated to the manual recalculation, and that the tax calculation on renewal order creation is not affected.

**Comment by devinsays** [comment]
Hi @dallendalton. Thanks for the quick follow up on this issue. We have been seeing renewal orders charge the tax. Here's the April renewal order for this customer.

<img width="801" alt="Screen Shot 2021-04-21 at 1 27 56 PM" src="https://user-images.githubusercontent.com/431879/115603220-80415180-a2a5-11eb-869e-86d3640f8f3c.png">

Let me know if there's anything you need on our side.

**Comment by dallendalton** [comment]
@devinsays - Thanks for the additional info. I haven't been able to duplicate the exemption not applying to the renewal yet, but will keep looking into it.

**Comment by dallendalton** [comment]
@devinsays - Thanks for your patience on this issue. We believe we have identified the root cause and should have a fix out early next week.

**Comment by dallendalton** [comment]
This issue was resolved.
