### ISSUE TITLE
Virtual item tax recalculation on account billing address changes

### ISSUE THREAD

**Issue by tyler-paulson** [taxjar/taxjar-woocommerce-plugin#202]
I work as a developer on [TBR](https://mytbr.co). We offer our subscription product in both physical and digital forms and collect tax on neither, one or both depending on the jurisdiction.

Here's out current setup:

```
WordPress 5.6.5
WooCommerce 5.5.2
WooCommerce Subscriptions 3.0.10
TaxJar 3.2.11
```

We noticed that when customers were updating the addresses for their subscriptions the sales tax amounts were not getting re-calculated. I put together some some custom code to handle this based on some advice I'd receive from you in the past. I lifted some code from the subscription plugin's `maybe_update_subscription_addresses()` function and had it trigger the `woocommerce_before_save_order_items` action.

``` php
function tbr_update_subscription_addresses_tax( $user_id, $address_type ) {

    if ( ! wcs_user_has_subscription( $user_id ) || wc_notice_count( 'error' ) > 0 || empty( $_POST['_wcsnonce'] ) || ! wp_verify_nonce( $_POST['_wcsnonce'], 'wcs_edit_address' ) ) {
        return;
    }

    $address_type   = ( 'billing' == $address_type || 'shipping' == $address_type ) ? $address_type : '';

    if ( isset( $_POST['update_all_subscriptions_addresses'] ) ) {

        $users_subscriptions = wcs_get_users_subscriptions( $user_id );

        foreach ( $users_subscriptions as $subscription ) {
            if ( $subscription->has_status( array( 'active', 'on-hold' ) ) ) {
                error_log('updating tax after address change for subscripion '.$subscription->get_id());
                do_action('woocommerce_before_save_order_items', $subscription->get_id(), $subscription->get_items());
                $subscription->calculate_totals();
                $subscription->save();
            }
        }
    }

}

add_action( 'woocommerce_customer_save_address', 'tbr_update_subscription_addresses_tax', 11, 2 );
```

The code seems to be working great for our subscribers who receive a physical box but we're having issues with our subscribers who receive their product virtually as as PDF download. When they switch their billing address, it seems like it's calculating the tax as if it's a physical product and applying tax in states that exempt virtual goods (like NY, where we are HQed).

Our physical and virtual offerings are variations of the same product.

We're currently not experiencing any issues with tax calculation with our physical / virtual variations on the checkout page.

I looked into the code the `woocommerce_before_save_order_items` action triggers and didn't see an immediate solution.

Could you point me to how I could adjust my code to avoid this issue? Or would it be possible for the TaxJar plugin to support recalculating tax for subscriptions when customers update their account address and tick the "update all subscriptions" checkbox?

**Comment by dallendalton** [comment]
@tkshredder Thanks for the additional information!

1. This is my understanding of how WooCommerce works by default as well. During checkout if a cart only contains virtual products only the billing address fields will be shown for input. If an order contains both physical and virtual products then checkout is normal (billing address fields shown with the option to set a separate shipping address).

However, when customers are updating their addresses through their "My Account" page and select to update all their subscriptions the same logic does not apply. If a customer edits their shipping address on the my account page and chooses to update their subscription addresses, that shipping address will be applied to all their subscriptions, regardless of if they are composed of only virtual products or not. So if a customer checkouts with a single virtual product and creates a subscription it will initially only have a billing address, which will then be used to calculate the tax. Then if they edit their addresses and update their shipping address on their subscriptions, TaxJar will then use that shipping address to calculate tax rather than the billing address. It should be easy to confirm if this is happening as the subscriptions with incorrect taxes will have a shipping address on them as well as a billing address.

2. Thanks for confirming which tax code you are using. If the information I gave above isn't the root cause, you may have to create a support request. That will allow us to take a look at your account and view the API requests coming from your store to see if the PTC is being sent correctly to TaxJar when these subscriptions are having their tax calculated. 

I've tested locally on a fresh WooCommerce site and I don't think the issue lies with the virtual products being a variation. In all the scenarios I've tested I haven't been able to replicate the wrong calculation (with the exception of changing the customers shipping address and applying it to all the subscriptions).

**Comment by tyler-paulson** [comment]
Thanks @dallendalton for your response! Your comment on the `woocommerce_before_save_order_items` action made me realize that we are running a rather dated version of the plugin (we don't have auto-updates enabled because of past issues with our custom code) and that's the root of our issue here. We updated the plugin in our test environment and our no longer experiencing the issue described above. We're still testing with some custom code we have in other parts of our application and will write back / contact support if we need help there. I'm going to close this issue for now.
