### ISSUE TITLE
Backend tax calculations cause fatal error with deleted items

### ISSUE THREAD

**Issue by v18** [taxjar/taxjar-woocommerce-plugin#68]
Heya! When trying to update an order with a product that has been deleted since the order was first placed, a user will encounter an error and won't be able to proceed.

**Steps to Repro**

1. Create an order with a product you can delete later
2. Delete the product permanently
3. Go to the Edit Order page and try to click the 'update' button. See fatal error.

This happens because `wc_get_product( $id )` ([ref](https://docs.woocommerce.com/wc-apidocs/function-wc_get_product.html)) returns `false` in https://github.com/taxjar/taxjar-woocommerce-plugin/blob/9d8e725186776f8c9628ebea59797a8fa41780ec/includes/class-wc-taxjar-integration.php#L617

To solve this, it's possible to use `$unit_price = $item->get_subtotal();` for getting the price and `'taxable' !== $item->get_tax_status()` for getting the tax status.

**Comment by joelwills** [comment]
Ticket for reference: 1146884-zen

**Comment by fastdivision** [comment]
@v18 @joelwills I believe we fixed this issue in v1.6 of TaxJar's plugin, but the change hasn't been ported over to WCS yet:

https://github.com/taxjar/taxjar-woocommerce-plugin/blob/4250146f571de0cf882d4718f20fb10756ba4106/includes/class-wc-taxjar-integration.php#L697-L699

Please see #57. Let me know if this doesn't fully address your issue. Thank you!

**Comment by jeffstieler** [comment]
> Let me know if this doesn't fully address your issue. Thank you!

My concern is that while this avoids a `PHP Fatal`, it will ignore deleted products that were part of an order which could lead to an incorrect tax calculation.

Example: I receive an order that buys out the remaining stock of a product I will no longer sell. I choose to delete the product after receiving that order. I recalculate taxes on the Edit Order screen, and since the product no longer exists it isn't included in the tax calculation.
